# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "dev"
# branch.

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

env:
  REGION: 'us-east4'
  CLOUD_RUN_SERVICE: 'mayberry-mini-trucks-dev'
  IMAGE: 'mayberry-mini-trucks-ui'

jobs:

  build:
    name: Build Image and Push Container to Registry
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up GCP SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use GCP CLI"
        run: "gcloud info"

      - name: "Docker Auth for GCP"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: 'Build and Push Container to GCP Artifact Registry'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ env.CLOUD_RUN_SERVICE }}/${{ env.IMAGE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"


  deploy:
    name: Deploy Container to Cloud Run
    needs: build
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.CLOUD_RUN_SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ env.CLOUD_RUN_SERVICE }}/${{ env.IMAGE }}:${{ github.sha }}'

      - name: 'Show output'
        run: |2-
          echo ${{ steps.deploy.outputs.url }}